name: MacOS Workflow
on: [push]

jobs:
  dotfiles:
    name: dotfiles
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install software updates
        run: make software_update

      - name: install dependencies
        run: make install_dependencies

      - name: install apps
        run: make install_apps

      - name: configure apps
        run: make configure_apps

      - name: apply custom preferences
        run: make apply_preferences
