name: MacOS Workflow
on: [push]

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"
          check_all_files_with_shebangs: "false"

  software_update:
    name: Software Update
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install software updates
        run: make software_update

  install:
      name: Install Dependencies and Apps
      runs-on: macos-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: install dependencies
          run: make install_dependencies

        - name: install apps
          run: make install_apps

  config:
      name: Install Dependencies and Apps
      runs-on: macos-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: install dependencies
          run: make install_dependencies

        - name: configure apps
          run: make configure_apps

        - name: apply custom preferences
          run: make apply_preferences

        - name: update history of executed commands
          run: make update_history_commands
